// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.show_abaris_box = function(selector, options) {
      if (options == null) {
        options = {};
      }
      $.extend(options, {
        wrapCSS: 'abaris-modal',
        padding: 5
      });
      console.log(options);
      return $.fancybox.open($(selector), options);
    };
  });

}).call(this);
