// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var form, hide_popover;
    $('.tooltip-msg').popover({
      html: true,
      trigger: 'hover'
    });
    $('.tooltip-msg').popover('show');
    hide_popover = function() {
      return $('.tooltip-msg').popover('destroy');
    };
    setTimeout(hide_popover, 2000);
    form = $('.abaris-form');
    return form.find(':radio').on('change', function() {
      if ($(this).attr('id') === 'ur') {
        return form.find('.organization').show();
      } else {
        return form.find('.organization').hide();
      }
    });
  });

}).call(this);
