// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('.spinner').spinner({
      min: 1,
      value: 1,
      icons: {
        down: "spinner-down",
        up: "spinner-up"
      }
    });
    $('.catalog-grid-header').scrollToFixed({
      limit: $('.subtotal').offset().top - $('.subtotal').height()
    });
    return $('.pay-icon').on('click', function(e) {
      var x, y;
      x = e.clientX;
      y = e.clientY;
      return $.show_abaris_box('.sto-modal', {
        beforeShow: function() {
          return $('.blue-button').on('click', function() {
            return $.fancybox.close();
          });
        }
      });
    });
  });

}).call(this);
