// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.show_abaris_box('.login-form');
    return $(".catalog-grid-row").hover(function() {
      if (!$(this).hasClass('no-hover')) {
        return $(this).addClass('active');
      }
    }, function() {
      return $(this).removeClass('active');
    });
    /*$('.catalog-grid-row').each () ->
    		max_height = 0
    		$(@).find('.field').each ()->
    			height = $(@).height()
    			max_height = height if max_height < height
    		$(@).find('.field').height(max_height)
    */

  });

}).call(this);
