// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('.grid-items .catalog-grid-row').on('click', function() {
      if ($(this).find('.check').length > 0) {
        $(this).find('.check').removeClass('check').addClass('un-check');
        return;
      }
      if ($(this).find('.un-check').length > 0) {
        $(this).find('.un-check').removeClass('un-check').addClass('check');
      }
    });
    return $.show_abaris_box = function(selector, options) {
      if (options == null) {
        options = {};
      }
      $.extend(options, {
        wrapCSS: 'abaris-modal',
        padding: 5
      });
      return $.fancybox.open($(selector), options);
    };
  });

}).call(this);
