// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var open_step1, open_step2, open_step3;
    $('.cancel-signup').on('click', function(e) {
      return $.fancybox.close();
    });
    open_step1 = function() {
      return $.fancybox.open($('.signup-step1'), {
        wrapCSS: "abaris-modal",
        padding: 5,
        afterShow: function() {
          return $('.signup-step1').find('.next-step').on('click', function() {
            return open_step2();
          });
        }
      });
    };
    open_step2 = function() {
      return $.fancybox.open($('.signup-step2'), {
        wrapCSS: "abaris-modal",
        padding: 5,
        afterShow: function() {
          $('.signup-step2').find('.next-step').on('click', function() {
            return open_step3();
          });
          return $('.signup-step2').find('.prev-step').on('click', function() {
            return open_step1();
          });
        }
      });
    };
    open_step3 = function() {
      return $.fancybox.open($('.signup-step3'), {
        wrapCSS: 'abaris-modal',
        padding: 5,
        afterShow: function() {
          return $('.signup-step3').find('.login-submit').on('click', function() {
            return $.fancybox.close();
          });
        }
      });
    };
    return open_step1();
  });

}).call(this);
