// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var open_step1, open_step2, open_step3;
    $('.cancel-signup').on('click', function() {
      return $.fancybox.close();
    });
    $('.add-auto').on('click', function() {
      var item, modal;
      modal = $(this).closest('.inline-modal');
      item = modal.find('.auto-item').eq(0).clone().addClass('clone-auto');
      item.find('input').val('');
      return modal.find('.auto-items').append(item);
    });
    open_step1 = function() {
      return $.show_abaris_box('.signup-step1', {
        afterShow: function() {
          var step1;
          step1 = $('.signup-step1');
          step1.find(':radio').on('change', function() {
            if ($(this).attr('id') === 'ur') {
              step1.find('.organization').show();
            } else {
              step1.find('.organization').hide();
            }
            return $.fancybox.update();
          });
          return step1.find('.next-step').on('click', function() {
            return open_step2();
          });
        }
      });
    };
    open_step2 = function() {
      return $.show_abaris_box('.signup-step2', {
        afterShow: function() {
          $('.signup-step2').find('.next-step').on('click', function() {
            return open_step3();
          });
          return $('.signup-step2').find('.prev-step').on('click', function() {
            return open_step1();
          });
        }
      });
    };
    open_step3 = function() {
      return $.show_abaris_box('.signup-step3', {
        autoCenter: false,
        afterShow: function() {
          return $('.signup-step3').find('.login-submit').on('click', function() {
            return $.fancybox.close();
          });
        }
      });
    };
    return open_step1();
  });

}).call(this);
